# Imagen base
FROM node:18

# Directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar TODO incluyendo devDependencies
RUN npm install --include=dev

# Copiar el resto
COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev"]
